In [64]:
import numpy as np

In [65]:
def multiplicacion_de_matrices(A, B):
    C = np.array([])
    if len(A[0]) == len(B):
        if len(B.shape) == 2:
            for i in range (len(A)):
                D = []
                for k in range(len(B[0])):
                    sum = 0
                    for j in range (len(B)):
                        sum += A[i, j]*B[j, k]
                    D.append(sum)
                C = np.append(C, D)
            return C.reshape(len(A), len(B[0]))
        else:
            for i in range (len(A[0])):
                sum = 0
                for j in range (len(B)):
                    sum += A[i, j]*B[j]
                C = np.append(C, sum)
            return C
    else:
        return "Las columnas de la primera matriz y las filas de la segunda no coinciden en número"

In [66]:
A = np.array([[5, -4, -2], [5, -5, 4], [2, 5, -4], [-5, 4, 3], [3, -4, -3]])
a = np.array([5, -2, -3])

In [67]:
multiplicacion_de_matrices(A, a)

array([39., 23., 12.])

In [68]:
B = np.array([[0, -1, -1, 3], [5, -5, -2, 2], [1, 0, 4, 5]])
b = np.array([[0, -3], [-2, -1], [3, -3]])

In [69]:
multiplicacion_de_matrices(B, b)

'Las columnas de la primera matriz y las filas de la segunda no coinciden en número'

In [70]:
C = np.array([[2, -5, 5, 1], [5, 2, -7, -6], [-6, -1, 7, -4], [5, 4, 1, -5]])
c = np.array([[0, 4, -7, 1, -6], [-1, -6, -5, 1, 1], [2, -1, -6, 5, -5], [-3, -6, 6, 3, 5]])

In [71]:
multiplicacion_de_matrices(C, c)

array([[ 12.,  27., -13.,  25., -37.],
       [  2.,  51., -39., -46., -23.],
       [ 27.,  -1., -19.,  16., -20.],
       [ 13.,  25., -91.,  -1., -56.]])

In [77]:
Matriz_Cuadrada_1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
Matriz_Cuadrada_2 = np.array([[-25, -24, -23, -22, -21], [-20, -19, -18, -17, -16], [-15, -14, -13, -12, -11], [-10, -9, -8, -7, -6], [-5, -4, -3, -2, -1]])

In [78]:
A = multiplicacion_de_matrices(Matriz_Cuadrada_1, Matriz_Cuadrada_2)
A

array([[ -175.,  -160.,  -145.,  -130.,  -115.],
       [ -550.,  -510.,  -470.,  -430.,  -390.],
       [ -925.,  -860.,  -795.,  -730.,  -665.],
       [-1300., -1210., -1120., -1030.,  -940.],
       [-1675., -1560., -1445., -1330., -1215.]])

In [79]:
B = multiplicacion_de_matrices(Matriz_Cuadrada_2, Matriz_Cuadrada_1)
B

array([[-1215., -1330., -1445., -1560., -1675.],
       [ -940., -1030., -1120., -1210., -1300.],
       [ -665.,  -730.,  -795.,  -860.,  -925.],
       [ -390.,  -430.,  -470.,  -510.,  -550.],
       [ -115.,  -130.,  -145.,  -160.,  -175.]])

In [80]:
def conmutatividad(A, B):
    if (A == B).all():
        return "La multiplicación de matrices es conmutativa en este caso"
    else: 
        return "La multiplicacion de matrices no es conmutativa"

In [81]:
conmutatividad(A, B)

'La multiplicacion de matrices no es conmutativa'